spring:
  security:
    oauth2:
      client:
        registration:
          your-client:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-name: Your Client
            client-authentication-method: post
        provider:
          your-provider:
            authorization-uri: https://your-provider.com/oauth2/authorize
            token-uri: https://your-provider.com/oauth2/token
            user-info-uri: https://your-provider.com/oauth2/userinfo
            jwk-set-uri: https://your-provider.com/oauth2/jwks
            user-name-attribute: sub